---
- name: Get latest github info
  uri:
    url: https://api.github.com/repos/ncw/rclone/releases/latest
    method: GET
    return_content: yes
  register: rclone_github_info
  check_mode: no

- name: Set/modify fact rclone_version
  set_fact:
    rclone_version: "{{ (rclone_github_info.content|from_json).tag_name }}"
  when: rclone_version == 'latest'
  check_mode: no

- name: Get installed rclone version info
  shell: "{{ rclone_executable.path }} --version"
  changed_when: false
  ignore_errors: true
  register: rclone_installed_info
  check_mode: no

- name: Install rclone from package repo
  package:
    name: '{{ rclone_repo_package }}'
    state: latest
  when:
    - rclone_install_from_github == False

- block:
    - name: Install packages
      package:
        name: '{{ item }}'
        state: latest
      with_items: '{{ rclone_packages }}'

    - name: Create tmp setup dir
      file:
        path: "{{ rclone_setup_tmp_dir}}"
        state: directory
        mode: 0775

    - name: "Download and unzip rclone-{{ rclone_version }}"
      unarchive:
        src: https://github.com/ncw/rclone/releases/download/{{ rclone_version }}/rclone-{{ rclone_version }}-linux-amd64.zip
        dest: "{{ rclone_setup_tmp_dir}}"
        copy: no
        creates: '{{ rclone_setup_tmp_dir }}"/rclone-{{ rclone_version }}-linux-amd64'

    - name: "Copy rclone-{{ rclone_version }} binary"
      copy:
        src: "{{ rclone_setup_tmp_dir}}/rclone-{{ rclone_version }}-linux-amd64/rclone"
        dest: "{{ rclone_executable.path }}"
        mode: 0755
        owner: "{{ rclone_executable.owner }}"
        group: "{{ rclone_executable.group }}"
        remote_src: true

    - name: Make dir for local manpages
      file:
        path: '{{ rclone_man_pages.path }}'
        state: directory
        mode: 0775
        owner: '{{ rclone_man_pages.owner }}'
        group: '{{ rclone_man_pages.group }}'

    - name: "Copy rclone-{{ rclone_version }} manpage"
      copy:
        src: "{{ rclone_setup_tmp_dir}}/rclone-{{ rclone_version }}-linux-amd64/rclone.1"
        dest: "{{ rclone_man_pages.path }}/rclone.1"
        mode: 0644
        owner: '{{ rclone_man_pages.owner }}'
        group: '{{ rclone_man_pages.group }}'
        remote_src: true
      notify: run mandb

  when:
    - rclone_installed_info.failed or (rclone_version not in rclone_installed_info.stdout_lines[0])
    - rclone_install_from_github == True
