---
- debug: var=ansible_os_family
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - vars

- name: rclone - define tmpdir
  set_fact:
    rclone_setup_tmp_dir: "/tmp/rclone_setup"

- name: Install required packages
  package:
    name: '{{ item }}'
    state: latest
  become: yes
  with_items: '{{ rclone_packages }}'

- name: install rclone - make temp dir
  file:
    path: "{{ rclone_setup_tmp_dir}}"
    state: directory
    mode: 0775

- name: install rclone - unzip package
  unarchive:
    src: https://github.com/ncw/rclone/releases/download/v{{ rclone_version }}/rclone-v{{ rclone_version }}-linux-amd64.zip
    dest: "{{ rclone_setup_tmp_dir}}"
    copy: no
    creates: '/tmp/rclone_setup/rclone-v{{ rclone_version }}-linux-amd64'
  become: yes

- name: install rclone - copy binary
  copy:
    src: "{{ rclone_setup_tmp_dir}}/rclone-v{{ rclone_version }}-linux-amd64/rclone"
    dest: "{{ rclone_executable.path }}"
    mode: 0755
    owner: "{{ rclone_executable.owner }}"
    group: "{{ rclone_executable.group }}"
    remote_src: true
  become: yes

- name: install rclone - make dir for local manpages
  file:
    path: '{{ rclone_man_pages.path }}'
    state: directory
    mode: 0775
    owner: '{{ rclone_man_pages.owner }}'
    group: '{{ rclone_man_pages.group }}'
  become: yes

- name: install rclone - copy manpage
  copy:
    src: "{{ rclone_setup_tmp_dir}}/rclone-v{{ rclone_version }}-linux-amd64/rclone.1"
    dest: "{{ rclone_man_pages.path }}/rclone.1"
    mode: 0644
    owner: root
    group: root
    remote_src: true
  become: yes

- name: install rclone - install manpage
  shell: mandb
  become: yes
  changed_when: false
